In [1]:
import numpy as np
print(np.__version__)


2.2.3


In [2]:
list=[10,20,30,40,50]
arr=np.array(list)
print(arr)
print('Type',type(arr))
print('shape',arr.shape)

[10 20 30 40 50]
Type <class 'numpy.ndarray'>
shape (5,)


In [4]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.shape)
print(arr1.size)
print(arr1[0])
print(arr1[0][2])


[[1 2 3]
 [4 5 6]]
(2, 3)
6
[1 2 3]
3


In [6]:
purchases=np.array([
    [200,250,100],[300,250,400],[100,200,150],[500,600,550],[50,80,100]])
total_speed=purchases.sum(axis=1)
average_speed=purchases.mean(axis=1)
print(total_speed)
print(average_speed)
print(max(average_speed))

[ 550  950  450 1650  230]
[183.33333333 316.66666667 150.         550.          76.66666667]
550.0


In [7]:
A=np.array([[2,3,],[4,1]])
B=np.array([8,10])
solution=np.linalg.solve(A,B)
print("Solution(x,y):",solution)



Solution(x,y): [2.2 1.2]


In [8]:
#Sales example assignment
sorted_employees = df.sort_values(by='Salary', ascending=False)

print(sorted_employees)
import numpy as np

sales_revenue = np.array([1000, 1500, 1200, 1800, 1100, 1700, 1400, 1600, 1300, 1900])

total_sales = np.sum(sales_revenue)
average_sales = np.mean(sales_revenue)
highest_sales = np.max(sales_revenue)
lowest_sales = np.min(sales_revenue)

days_above_average = np.where(sales_revenue > average_sales)[0] + 1
increased_sales = sales_revenue * 1.10
sorted_sales = np.sort(increased_sales)

print(f"Days with sales above average: {days_above_average}")
print(f"Total Sales: {total_sales}")
print(f"Average Sales: {average_sales}")
print(f"Highest Sales: {highest_sales}")
print(f"Lowest Sales: {lowest_sales}")
print(f"Sales with 10% increase: {increased_sales}")
print(f"Sorted Sales (Ascending Order): {sorted_sales}")


Days with sales above average: [ 2  4  6  8 10]
Total Sales: 14500
Average Sales: 1450.0
Highest Sales: 1900
Lowest Sales: 1000
Sales with 10% increase: [1100. 1650. 1320. 1980. 1210. 1870. 1540. 1760. 1430. 2090.]
Sorted Sales (Ascending Order): [1100. 1210. 1320. 1430. 1540. 1650. 1760. 1870. 1980. 2090.]


In [2]:
import pandas as pd
 
df = pd.read_csv('sales_data.csv')
 
print(df)
 
 
df.info()
 
df.isnull()
 
df.fillna(0)

   Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           NaN   
1      1002  Mobile Phone  Electronics         1    500           NaN   
2      1003    Headphones  Accessories         3     50           NaN   
3      1004         Mouse  Accessories         2     20           NaN   
4      1005      Keyboard  Accessories         1     30           NaN   
5      1006       T-shirt     Clothing         4     15           NaN   
6      1007        Jacket     Clothing         1     60           NaN   
7      1008  Refrigerator  Electronics         1    900           NaN   
8      1009            TV  Electronics         2   1100           NaN   
9      1010         Shoes     Clothing         2     40           NaN   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10  
<class 'pandas.core.

Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           0.0   
1      1002  Mobile Phone  Electronics         1    500           0.0   
2      1003    Headphones  Accessories         3     50           0.0   
3      1004         Mouse  Accessories         2     20           0.0   
4      1005      Keyboard  Accessories         1     30           0.0   
5      1006       T-shirt     Clothing         4     15           0.0   
6      1007        Jacket     Clothing         1     60           0.0   
7      1008  Refrigerator  Electronics         1    900           0.0   
8      1009            TV  Electronics         2   1100           0.0   
9      1010         Shoes     Clothing         2     40           0.0   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10

In [3]:
df.isnull()

Order_ID  Product  Category  Quantity  Price  Total_Amount   Date
0     False    False     False     False  False          True  False
1     False    False     False     False  False          True  False
2     False    False     False     False  False          True  False
3     False    False     False     False  False          True  False
4     False    False     False     False  False          True  False
5     False    False     False     False  False          True  False
6     False    False     False     False  False          True  False
7     False    False     False     False  False          True  False
8     False    False     False     False  False          True  False
9     False    False     False     False  False          True  False

In [4]:
df.isna()

Order_ID  Product  Category  Quantity  Price  Total_Amount   Date
0     False    False     False     False  False          True  False
1     False    False     False     False  False          True  False
2     False    False     False     False  False          True  False
3     False    False     False     False  False          True  False
4     False    False     False     False  False          True  False
5     False    False     False     False  False          True  False
6     False    False     False     False  False          True  False
7     False    False     False     False  False          True  False
8     False    False     False     False  False          True  False
9     False    False     False     False  False          True  False

In [5]:
df.fillna(0)

Order_ID       Product     Category  Quantity  Price  Total_Amount  \
0      1001        Laptop  Electronics         2    700           0.0   
1      1002  Mobile Phone  Electronics         1    500           0.0   
2      1003    Headphones  Accessories         3     50           0.0   
3      1004         Mouse  Accessories         2     20           0.0   
4      1005      Keyboard  Accessories         1     30           0.0   
5      1006       T-shirt     Clothing         4     15           0.0   
6      1007        Jacket     Clothing         1     60           0.0   
7      1008  Refrigerator  Electronics         1    900           0.0   
8      1009            TV  Electronics         2   1100           0.0   
9      1010         Shoes     Clothing         2     40           0.0   

         Date  
0  2024-02-01  
1  2024-02-02  
2  2024-02-03  
3  2024-02-04  
4  2024-02-05  
5  2024-02-06  
6  2024-02-07  
7  2024-02-08  
8  2024-02-09  
9  2024-02-10

In [6]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [10]:
df.dtypes

Order_ID          int64
Product          object
Category         object
Quantity          int64
Price             int64
Total_Amount    float64
Date             object
dtype: object

In [12]:
df.duplicated()
 
df.dtypes
 
df['Date']=pd.to_datetime(df['Date'])
 
df.dtypes
 
type("HelloWorls")
 



str

In [10]:
import numpy as np
data = np.array([10,12,23,43,12,32,100])

Q1 = np.percentile(data, 10)
Q3 = np.percentile(data, 45)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = data[(data < lower_bound) | (data > upper_bound)]
print("Outliers: ", outliers)


Outliers:  [ 43 100]
